"""
Django settings for recipe_web project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAIN_TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'bzyjrsylze82ev_j2y4o3zju$sjkug^_w&f(88ii4=178z9t7m'

import json_log_formatter

class CustomisedJSONFormatter(json_log_formatter.JSONFormatter):
    def json_record(self, message, extra, record):
        self.datefmt = "%Y-%m-%d %H:%M:%S"
        # extra['message'] = message
        extra['asctime'] = self.formatTime(record, self.datefmt)
        # extra['funcName'] = record.__dict__['funcName']
        # extra['levelname'] = record.__dict__['levelname']
        # extra['name'] = record.__dict__['name']f
        # extra['lineno'] = record.__dict__['lineno']
        # extra['filename'] = record.__dict__['filename']
        # extra['pathname'] = record.__dict__['pathname']
        # extra['asctime'] = record.__dict__['asctime']
        # extra['created'] = record.__dict__['created']
        # request = extra.pop('request', None)
        # if request:
        #     extra['x_forward_for'] = request.META.get('X-FORWARD-FOR') # IP주소를 가져옴
        return extra

    
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
        "formatters": {
        "verbose": {
            "format": "{asctime} {message} {funcName}",
            "style": "{",
        },
        'standard': {
            'format' : "[%(asctime)s] %(levelname)s %(name)s:%(lineno)s %(message)s",
            'datefmt' : "%Y-%m-%d %H:%M:%S"
        },
        "json":{
            "()": CustomisedJSONFormatter,
        }
    },
    "handlers": {
        "file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, 'logsfolder') + "/log1.log",
            "formatter": "verbose",
        },
        "file2": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, 'logsfolder') + "/json_log.log",
            "formatter": "json",
        },
    },
    "loggers": {
        'file': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
        'file2': {
            'handlers': ['file2'],
            'level': 'INFO',
            'propagate': False,
        }

    },
}


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['15.168.111.154']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'posts',
    'accounts',
    
    'bootstrap5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'recipe_web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ MAIN_TEMPLATE_DIR ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'recipe_web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', # 사용할 데이터베이스 엔진
        'NAME': 'recipe_db', # 데이터베이스 이름 
        'USER': 'multi01', # 접속할 Database 계정 아이디 ex) root
        'PASSWORD': '1111',  # 접속할 Database 계정 비밀번호 ex) 1234
        'HOST': '15.168.111.154',   # host는 로컬 환경에서 동작한다면 ex) localhost
        'PORT': '3306', # 설치시 설정한 port 번호를 입력한다. ex) 3306
        'OPTIONS': {
    'auth_plugin': 'mysql_native_password',  # 'caching_sha2_password' 대신 'mysql_native_password' 사용
}
    }
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

AUTH_USER_MODEL = 'accounts.User'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/' 